---
title: "{{cookiecutter.project_name}}"
description: |
  "{{cookiecutter.project_desc}}"
author:
  - name: "{{cookiecutter.full_name}}",
    orcid_id: "{{cookiecutter.orcid_id}}",
    url: "{{cookiecutter.personal_url}}"
    affiliation: "{{cookiecutter.affiliation}}"
    affiliation_url: "{{cookiecutter.affiliation_url}}"
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```

Welcome to the "{{cookiecutter.project_slug}}". This site focuses on providing more details on the analytical portion and is a supplement to the manuscript site.

The folders herein are designed for the following:

* *_store-[data|figures|resources|tables]* : central place to store objects; when possible, should be linked to a specific data object generated by a notebook
  * *_store-data* is a slightly special case, in that this area can/should contain:
    * *_data-raw* - raw data (which may or may not be amenable to version control; if the file is large or binary or too numerous add to .gitignore)
    * *_data-exec* - scripts used to preprocess raw data into a form amenable to analysis by scripts within notebooks
* *_eda* - exploratory data analyses; this is a playground that can be organized as best suited to your needs
* *_notebooks* - the center of the analysis area
  * *01_first-objective* - notebooks should be organized by a central objective and be units that can be portably transferred to others (should all the necessary inputs/outputs be provided)
    * *_figures*, *_tables*, *_input*, *_output* - artifacts read in or produced by the scripts herein
    * *01_first-step.Rmd* - each script organized sequentially
  * *...*
*